ConnectorSettingsScreen:
    id: ethernetsrc
    orientation: 'vertical'
    MDBoxLayout:
        orientation: 'horizontal'
        pos_hint: {'center_x': 0.5, 'center_y': 0.9}
        spacing: (12dp)

        MDLabel:
            text: "TYPE"
        MDTextField:
            hint_text: "Ethernet type"
        MDLabel: 
            text: "Protocol selection"
        MDTextField:
            hint_text: "Select connection protocol"
        
    
    